### Webapp build
FROM node:16.3.0@sha256:ca6daf1543242acb0ca59ff425509eab7defb9452f6ae07c156893db06c7a9a4 as nodebuild

WORKDIR /webapp
# package.json is required by npm at build stage
# need additional setup for node_modules
ADD webapp/ ./

ENV NODE_OPTIONS=--max_old_space_size=4096
VOLUME /webapp/pack

### 'CPPFLAGS="-DPNG_ARM_NEON_OPT=0"' Needed To Avoid Bug Described in: https://github.com/imagemin/optipng-bin/issues/118#issuecomment-1019838562
### Can be Removed when Ticket will be Closed
RUN CPPFLAGS="-DPNG_ARM_NEON_OPT=0" npm install --no-optional
# Run app in hot reload mode - recompile whenever files change
CMD ["npm", "run", "watchdev"]
